# Site Configuration
title: Lars van Blitterswijk
tagline: Tech and Security Enthusiast
description: >-
  Welcome! My name is Lars and this is my corner of the digital realm. 
  I spend my days weaving security into the fabric of technology, 
  crafting digital defenses against the shadows of cyberspace.

url: 'https://larsjelle.github.io'
baseurl: ''

# Author
author:
  name: Lars van Blitterswijk
  email: contact@larsjelle.nl
  url: https://larsjelle.github.io

# Social Links
github_username: larsjelle
twitter_username: Larsjelle18
linkedin_url: https://www.linkedin.com/in/lars-van-blitterswijk/
instagram_url: https://www.instagram.com/larsjelle/

# Site Settings
timezone: Europe/Amsterdam
lang: en
permalink: /posts/:title/

# Avatar
avatar: https://avatars.githubusercontent.com/u/18476229?v=4

# Theme Mode
theme_mode: # Leave empty for system preference

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - _backup/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - package.json
  - package-lock.json
